/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hpe.pss.view;

import com.hpe.pass.util.LocationUtil;
import com.hpe.pass.util.StringUtil;
import com.hpe.pss.biz.CustomerBiz;
import com.hpe.pss.biz.CustomerBizImpl;
import com.hpe.work.po.Customer;

import java.math.BigDecimal;

import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author admin
 */
public class CustomerIFrame extends javax.swing.JInternalFrame {
    CustomerBiz pbiz = new CustomerBizImpl();
     public static LocationUtil local;
    /**
     * Creates new form customerFrame
     */
    public CustomerIFrame() {
        initComponents();
         local.setScreenCenter(this);
        this.btnsave.setEnabled(false);
        this.btndelete.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblcustomer = new javax.swing.JTable();
        bthsearch = new javax.swing.JButton();
        txtcondition = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtcusid = new javax.swing.JTextField();
        txtcusidabc = new javax.swing.JLabel();
        txtcustelabc = new javax.swing.JLabel();
        txtcustel = new javax.swing.JTextField();
        txtnameabc = new javax.swing.JLabel();
        txtcusaddrabc = new javax.swing.JLabel();
        txtcusname = new javax.swing.JTextField();
        txtcusaddr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtMoblie = new javax.swing.JTextField();
        btnlog = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();

        setClosable(true);
        setTitle("客户管理");

        tblcustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "客户编号", "客户名称", "客户手机", "客户电话", "客户地址"
            }
        ));
        tblcustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblcustomer);

        bthsearch.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        bthsearch.setText("查询");
        bthsearch.setToolTipText("以客户名称或编号为关键字");
        bthsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthsearchActionPerformed(evt);
            }
        });

        txtcusid.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        txtcusid.setEnabled(false);

        txtcusidabc.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        txtcusidabc.setText("客户编号");

        txtcustelabc.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        txtcustelabc.setText("客户手机");

        txtcustel.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        txtnameabc.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        txtnameabc.setText("客户名称");

        txtcusaddrabc.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        txtcusaddrabc.setText("客户地址");

        txtcusname.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        txtcusaddr.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel1.setText("客户电话");

        txtMoblie.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtcusidabc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtcustelabc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtcusaddrabc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcustel, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcusid, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtnameabc))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMoblie, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcusname, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtcusaddr, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnameabc)
                    .addComponent(txtcusidabc)
                    .addComponent(txtcusid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcusname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcustelabc)
                    .addComponent(txtcustel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtMoblie))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcusaddrabc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcusaddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnlog.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnlog.setText("载入");
        btnlog.setToolTipText("加载全部客户信息");
        btnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogActionPerformed(evt);
            }
        });

        btnadd.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnadd.setText("新增");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnsave.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnsave.setText("修改并保存");
        btnsave.setToolTipText("更新客户信息");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btncancel.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btncancel.setText("取消");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        btnexit.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnexit.setText("退出");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btndelete.setText("删除");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnlog)
                        .addGap(36, 36, 36)
                        .addComponent(btnadd)
                        .addGap(35, 35, 35)
                        .addComponent(btnsave)
                        .addGap(43, 43, 43)
                        .addComponent(btncancel)
                        .addGap(19, 19, 19)
                        .addComponent(btnexit)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btndelete)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtcondition, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(bthsearch)
                .addGap(463, 463, 463))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bthsearch)
                    .addComponent(txtcondition, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlog)
                    .addComponent(btnadd)
                    .addComponent(btncancel)
                    .addComponent(btnexit)
                    .addComponent(btndelete)
                    .addComponent(btnsave))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        int cusid = Integer.parseInt(this.txtcusid.getText());
        String cusname = this.txtcusname.getText().trim();
        String custel = this.txtcustel.getText().trim();
        String cusaddr = this.txtcusaddr.getText().trim();
        String cusmoblie = this.txtMoblie.getText().trim();
       
        if(StringUtil.checkLength(cusname) == false){
            JOptionPane.showMessageDialog(this, "类型为空");
            return;
        }
        if(StringUtil.checkLength(custel) == false){
            JOptionPane.showMessageDialog(this, "类型为空");
            return;
        }
        if(StringUtil.checkLength(cusaddr) == false){
            JOptionPane.showMessageDialog(this, "类型为空");
            return;
        }
    
        Customer p = new Customer(cusid,cusname,custel,cusmoblie,cusaddr);
        boolean result = pbiz.update(p);
        if(result == true){
            JOptionPane.showMessageDialog(this,"修改成功");
            List<Customer> list = pbiz.findAll();
            showOnTable(list);
        }else{
             JOptionPane.showMessageDialog(this,"修改失败");
        }
        //清空面板
        clearInput();
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogActionPerformed
        List<Customer> list = pbiz.findAll();
        showOnTable(list);
    }//GEN-LAST:event_btnlogActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        String cusname = this.txtcusname.getText().trim();
        String custel = this.txtcustel.getText().trim();
        String cusmoblie = this.txtMoblie.getText().trim();
        String cusaddr = this.txtcusaddr.getText().trim();
        if(StringUtil.checkLength(cusname) == false){
            JOptionPane.showMessageDialog(this, "类型为空");
            return;
        }
      
        if(StringUtil.checkLength(custel) == false){
            JOptionPane.showMessageDialog(this, "类型为空");
            return;
        }
        if(StringUtil.checkLength(cusaddr) == false){
            JOptionPane.showMessageDialog(this, "类型为空");
            return;
        }
        Customer p = new Customer(null,cusname,custel,cusmoblie,cusaddr);
        boolean result = pbiz.add(p);
        if(result == true){
            JOptionPane.showMessageDialog(this,"添加成功");
            List<Customer> list = pbiz.findAll();
            showOnTable(list);
        }else{
             JOptionPane.showMessageDialog(this,"添加失败");
        }
        //清空面板
        clearInput();
    }//GEN-LAST:event_btnaddActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        int answer = JOptionPane.showConfirmDialog(this,"您确定要删除吗？");
        if(answer == JOptionPane.YES_OPTION){
             //删除商品
             int cusid = Integer.parseInt(this.txtcusid.getText());
            boolean result = pbiz.delete(cusid);   
            if(result == true){
                 JOptionPane.showMessageDialog(this,"删除成功");
                 List<Customer> list = pbiz.findAll();
                showOnTable(list);
             }else{
            JOptionPane.showMessageDialog(this,"删除失败");
             }
        }else{
             JOptionPane.showMessageDialog(this,"取消删除");
        }
        
       
        //清空面板
        clearInput();
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        clearInput();
        this.btnsave.setEnabled(false);
        this.btndelete.setEnabled(false);
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
         this.dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    private void bthsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthsearchActionPerformed
        String condition = this.txtcondition.getText().trim();
        List<Customer> list = pbiz.findByCondition(condition);
        showOnTable(list);
    }//GEN-LAST:event_bthsearchActionPerformed

    private void tblcustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcustomerMouseClicked
        // TODO add your handling code here:
        int row = this.tblcustomer.getSelectedRow();
        this.txtcusid.setText(this.tblcustomer.getValueAt(row ,0)+"");
        this.txtcusname.setText(this.tblcustomer.getValueAt(row, 1)+"");
        this.txtcustel.setText(this.tblcustomer.getValueAt(row, 2)+"");
        this.txtMoblie.setText(this.tblcustomer.getValueAt(row, 3)+"");
        this.txtcusaddr.setText(this.tblcustomer.getValueAt(row, 4)+"");
        this.btndelete.setEnabled(true);
        this.btnsave.setEnabled(true);
       
    }//GEN-LAST:event_tblcustomerMouseClicked
public void clearInput(){
    this.txtcusid.setText("");
    this.txtcusname.setText("");
    this.txtcustel.setText("");
    this.txtMoblie.setText("");
    this.txtcusaddr.setText("");
    

}
public void showOnTable( List<Customer> list){
        //1.获取制定表格（tblProduct）模型
        DefaultTableModel dtm = (DefaultTableModel) this.tblcustomer.getModel();
        //2.清空表格信息
        while(dtm.getRowCount() > 0){
            dtm.removeRow(0);
        }
        //3.显示数据
        for(Customer p : list){
            Vector vt = new Vector();
            vt.add(p.getCusid());
            vt.add(p.getCusname()); 
            vt.add(p.getCustel());
            vt.add(p.getCusmobile());
            vt.add(p.getCusaddr());
           dtm.addRow(vt);
        }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bthsearch;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnlog;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblcustomer;
    private javax.swing.JTextField txtMoblie;
    private javax.swing.JTextField txtcondition;
    private javax.swing.JTextField txtcusaddr;
    private javax.swing.JLabel txtcusaddrabc;
    private javax.swing.JTextField txtcusid;
    private javax.swing.JLabel txtcusidabc;
    private javax.swing.JTextField txtcusname;
    private javax.swing.JTextField txtcustel;
    private javax.swing.JLabel txtcustelabc;
    private javax.swing.JLabel txtnameabc;
    // End of variables declaration//GEN-END:variables

}
