/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hpe.pss.view;

import com.hpe.pass.util.ExportExcel;
import com.hpe.pass.util.LocationUtil;
import com.hpe.pss.biz.CustradeBiz;
import com.hpe.pss.biz.CustradeBizImpl;
import com.hpe.pss.vo.View_Custrade;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class CustradeFrame extends javax.swing.JInternalFrame {
    public static LocationUtil local;
    List list;
    CustradeBiz pbiz = new CustradeBizImpl(); 
    /**
     * Creates new form cusTradeFrame
     */
    public CustradeFrame() {
        initComponents();
        local.setScreenCenter(this);
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblcustrade = new javax.swing.JTable();
        btnlodin = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        txtstart = new com.hpe.pass.util.DateChooserJButton();
        txtend = new com.hpe.pass.util.DateChooserJButton();
        btnsearch = new javax.swing.JButton();

        setClosable(true);
        setTitle("客户交易统计");

        tblcustrade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "客户编号", "客户名称", "总金额"
            }
        ));
        jScrollPane1.setViewportView(tblcustrade);

        btnlodin.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnlodin.setText("载入");
        btnlodin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlodinActionPerformed(evt);
            }
        });

        btnexit.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnexit.setText("退出");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        btnprint.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnprint.setText("打印报表");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        txtstart.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        txtend.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        btnsearch.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnsearch.setText("查询");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnlodin)
                .addGap(37, 37, 37)
                .addComponent(btnprint)
                .addGap(59, 59, 59)
                .addComponent(btnexit)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(txtstart, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(txtend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsearch)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(txtstart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlodin)
                    .addComponent(btnexit)
                    .addComponent(btnprint))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlodinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlodinActionPerformed
        list = pbiz.findAll();
        showOnTable(list);
    }//GEN-LAST:event_btnlodinActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        JFileChooser savefile = new JFileChooser();//文件选择对话框
        FileFilter filter = new FileNameExtensionFilter("Excel文件(*.xls)", "xls");
        savefile.addChoosableFileFilter(filter);//添加过滤器
        savefile.setFileFilter(filter);

        int flag = savefile.showSaveDialog(this);//打开文件选选择对话框
        File file = null;
        if (flag == JFileChooser.APPROVE_OPTION) {
        //如果点击了保存按钮
        file = savefile.getSelectedFile();//所选择的文件名（手写或选择）
        System.out.println("文件名：" + file.getAbsolutePath());
        String filename = file.getAbsolutePath();
        //截取文件扩展名（文件名长度后4位）
        String ftype = filename.substring(filename.length()-4);
        if(!ftype.equals(".xls")){
            //如果用户没有填写扩展名，自动添加扩展名.xls
            file = new File(filename+".xls");
        }
        //集合获取数据，输出到文件
        ExportExcel.printCustrade(list, file);
        list.clear();
    }
    }//GEN-LAST:event_btnprintActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
         String start = this.txtstart.getText().trim();
        String end = this.txtend.getText().trim();
        list =pbiz.findCondition(start,end);
        showOnTable(list);
    }//GEN-LAST:event_btnsearchActionPerformed

    public void refreshTable(){
        if(list==null)return;
        DefaultTableModel dtm = (DefaultTableModel) this.tblcustrade.getModel();
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
        }
        for(View_Custrade ps:(List<View_Custrade>)list){
            Vector vt = new Vector();
            vt.add(ps.getCusid());
            vt.add(ps.getCusname());
            vt.add(ps.getSellmon());
           
            dtm.addRow(vt);
        }
    }
    private void showOnTable(List<View_Custrade> list) {
     
        //1.获取制定表格（tblProduct）模型
        DefaultTableModel dtm = (DefaultTableModel) this.tblcustrade.getModel();
        //2.清空表格信息
        while(dtm.getRowCount() > 0){
            dtm.removeRow(0);
        }  //    refreshTable();
        //3.显示数据
        for(View_Custrade ps : list){
            Vector vt = new Vector();
            vt.add(ps.getCusid());
            vt.add(ps.getCusname());
            vt.add(ps.getSellmon());
           dtm.addRow(vt);
           list.add(ps);
        }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnlodin;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnsearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblcustrade;
    private com.hpe.pass.util.DateChooserJButton txtend;
    private com.hpe.pass.util.DateChooserJButton txtstart;
    // End of variables declaration//GEN-END:variables
}
