/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hpe.pss.view;

import com.hpe.pass.util.LocationUtil;
import com.hpe.pss.biz.ProductBiz;
import com.hpe.pss.biz.ProductBizImpl;
import com.hpe.work.po.Product;
import java.math.BigDecimal;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class ProductIFrame extends javax.swing.JInternalFrame {
 ProductBiz pbiz = new ProductBizImpl();
  public static LocationUtil local;
    /**
     * Creates new form ProductFrame1
     */
    public ProductIFrame() {
        initComponents();
        local.setScreenCenter(this);
        this.btnsave.setEnabled(false);
        this.btndelete.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblproduct = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtproid = new javax.swing.JTextField();
        txtproname = new javax.swing.JTextField();
        txtprotype = new javax.swing.JTextField();
        txtsafe = new javax.swing.JTextField();
        txtpropurchase = new javax.swing.JTextField();
        txtprosell = new javax.swing.JTextField();
        txtlastpurchase = new javax.swing.JTextField();
        txtlastsell = new javax.swing.JTextField();
        lbl = new javax.swing.JLabel();
        txtcurrent = new javax.swing.JTextField();
        btnlodin = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        txtcondition = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("商品管理");

        tblproduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "商品编号", "商品名称", "商品型号", "安全数量", "建议采购价", "建议销售价", "库存", "最后采购日期", "最后销售日期"
            }
        ));
        tblproduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblproductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblproduct);

        jLabel1.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel1.setText("商品编号：");

        jLabel2.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("商品名称：");

        jLabel3.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel3.setText("商品型号：");

        jLabel4.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel4.setText("安全数量：");

        jLabel5.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel5.setText("建议采购价：");

        jLabel6.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel6.setText("建议销售价：");

        jLabel8.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel8.setText("最后采购日期：");

        jLabel9.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel9.setText("最后销售日期：");

        txtproid.setEditable(false);
        txtproid.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        txtproname.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        txtprotype.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        txtsafe.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        txtpropurchase.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        txtprosell.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        txtlastpurchase.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        txtlastsell.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        lbl.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        lbl.setText("库存：");

        txtcurrent.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtproid, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(lbl))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsafe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcurrent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(157, 157, 157)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpropurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtproname, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtlastpurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtprotype, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(txtprosell)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtlastsell, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtproid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprotype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtproname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(txtsafe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprosell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtpropurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlastpurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtlastsell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        btnlodin.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnlodin.setText("载入");
        btnlodin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlodinActionPerformed(evt);
            }
        });

        btnadd.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnadd.setText("新增");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnsave.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnsave.setText("修改并保存");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btndelete.setText("删除");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnupdate.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnupdate.setText("取消");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btnexit.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnexit.setText("退出");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        btnsearch.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnsearch.setText("查询");
        btnsearch.setToolTipText("在左边输入查询条件");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        txtcondition.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("注意：红色字体项目为必填！");

        jButton1.setText("上一页");
        jButton1.setEnabled(false);

        jButton2.setText("下一页");
        jButton2.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtcondition, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnsearch)
                .addGap(348, 348, 348))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(344, 344, 344)
                        .addComponent(btnlodin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnadd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btndelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnupdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnexit))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(jButton1)
                        .addGap(41, 41, 41)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsearch)
                    .addComponent(txtcondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnlodin)
                        .addComponent(btnadd)
                        .addComponent(btnsave)
                        .addComponent(btndelete)
                        .addComponent(btnupdate)
                        .addComponent(btnexit)))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlodinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlodinActionPerformed
        // TODO add your handling code here:List<Customer> list = pbiz.findAll();
        List<Product> list = pbiz.findAll();
        showOnTable(list);
    }//GEN-LAST:event_btnlodinActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        String proname = this.txtproname.getText().trim();
        String type = this.txtprotype.getText().trim();
        String safe = this.txtsafe.getText().trim();
        String sugp = this.txtpropurchase.getText().trim();
        String sugs = this.txtprosell.getText().trim();
        String current = this.txtcurrent.getText().trim();
        String lsd = this.txtlastsell.getText().trim();
        String lpd = this.txtlastpurchase.getText().trim();
        Integer safeamount = Integer.parseInt(safe);
        Integer storecount = Integer.parseInt(current);
        BigDecimal sugpurchase = new BigDecimal(sugp);
        BigDecimal sugsell = new BigDecimal(sugs);
        java.sql.Date lastpurchase = java.sql.Date.valueOf(lpd);
        java.sql.Date lastsale = java.sql.Date.valueOf(lsd);
        //java.sql.Date lastpurchase = java.sql.Date.valueOf(lastpurchase_s);
        Product p = new Product(null,proname,type,safeamount,sugpurchase,sugsell,storecount,lastpurchase,lastsale);
        boolean result = pbiz.add(p);
        if(result == true){
            JOptionPane.showMessageDialog(this,"添加成功");
            List<Product> list = pbiz.findAll();
            showOnTable(list);
        }else{
            JOptionPane.showMessageDialog(this,"添加失败");
        }
        //清空面板
        clearInput();

    }//GEN-LAST:event_btnaddActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        int proid = Integer.parseInt(this.txtproid.getText());
        String proname = this.txtproname.getText().trim();
        String type = this.txtprotype.getText().trim();
        String safe = this.txtsafe.getText().trim();
        String sugp = this.txtpropurchase.getText().trim();
        String sugs = this.txtprosell.getText().trim();
        String current = this.lbl.getText().trim();
        String lsd = this.txtlastsell.getText().trim();
        String lpd = this.txtlastpurchase.getText().trim();
        Integer safeamount = Integer.parseInt(safe);
        Integer currentcount = Integer.parseInt(current);
        BigDecimal sugpurchase = new BigDecimal(sugp);
        BigDecimal sugsell = new BigDecimal(sugs);
        java.sql.Date lastpurchase = java.sql.Date.valueOf(lpd);
        java.sql.Date lastsale = java.sql.Date.valueOf(lsd);
        //java.sql.Date lastpurchase = java.sql.Date.valueOf(lastpurchase_s);
        Product p = new Product(proid,proname,type,safeamount,sugpurchase,sugsell,currentcount,lastpurchase,lastsale);

        boolean result = pbiz.update(p);
        System.out.println(result);
        if(result == true){
            JOptionPane.showMessageDialog(this,"修改成功");
            List<Product> list = pbiz.findAll();
            showOnTable(list);
        }else{
            JOptionPane.showMessageDialog(this,"修改失败");
        }
        //清空面板
        clearInput();
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        int answer = JOptionPane.showConfirmDialog(this,"您确定要删除吗？");
        if(answer == JOptionPane.YES_OPTION){
            //删除商品
            int supid = Integer.parseInt(this.txtproid.getText());
            boolean result = pbiz.delete(supid);
            System.out.println(result);
            if(result == true){
                JOptionPane.showMessageDialog(this,"删除成功");
                List<Product> list = pbiz.findAll();
                showOnTable(list);
            }else{
                JOptionPane.showMessageDialog(this,"删除失败");
            }
        }else{
            JOptionPane.showMessageDialog(this,"取消删除");
        }
        //清空面板
        clearInput();
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        clearInput();
        this.btnsave.setEnabled(false);
        this.btndelete.setEnabled(false);
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    private void tblproductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblproductMouseClicked
        int row = this.tblproduct.getSelectedRow();
        this.txtproid.setText(this.tblproduct.getValueAt(row ,0)+"");
        this.txtproname.setText(this.tblproduct.getValueAt(row, 1)+"");
        this.txtprotype.setText(this.tblproduct.getValueAt(row, 2)+"");
        this.txtsafe.setText(this.tblproduct.getValueAt(row, 3)+"");
        this.txtpropurchase.setText(this.tblproduct.getValueAt(row, 4)+"");
        this.txtprosell.setText(this.tblproduct.getValueAt(row, 5)+"");
        this.txtcurrent.setText(this.tblproduct.getValueAt(row, 6)+"");
        this.txtlastpurchase.setText(this.tblproduct.getValueAt(row, 7)+"");
        this.txtlastsell.setText(this.tblproduct.getValueAt(row, 8)+"");
  
        this.btndelete.setEnabled(true);
       this.btnsave.setEnabled(true);
    }//GEN-LAST:event_tblproductMouseClicked

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        String condition = this.txtcondition.getText().trim();
        List<Product> list = pbiz.findByCondition(condition);
        showOnTable(list);
    }//GEN-LAST:event_btnsearchActionPerformed

    private void tblproductFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblproductFocusGained
        //String name=(String)tblproduct.getValueAt(tblproduct.getSelectedRow(),0);
        
    }//GEN-LAST:event_tblproductFocusGained

    public void showOnTable( List<Product> list){
        //1.获取制定表格（tblProduct）模型
        DefaultTableModel dtm = (DefaultTableModel) this.tblproduct.getModel();
        //2.清空表格信息
        while(dtm.getRowCount() > 0){
            dtm.removeRow(0);
        }
        //3.显示数据
        for(Product p : list){
            Vector vt = new Vector();
            vt.add(p.getProid());
            vt.add(p.getProname()); 
            vt.add(p.getType());
            vt.add(p.getSafeamount());
            vt.add(p.getSugpurchase());
            vt.add(p.getSugsell());
            vt.add(p.getStorecount());
            vt.add(p.getLastpurchase());
            vt.add(p.getLastsale());
           dtm.addRow(vt);
        }
}
    public void clearInput(){
  this.txtproid.setText("");
    this.txtproname.setText("");
    this.lbl.setText("");
    this.txtlastpurchase.setText("");
    this.txtlastsell.setText("");
    this.txtpropurchase.setText("");
    this.txtprosell.setText("");
    this.txtprotype.setText("");
    this.txtsafe.setText("");
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnlodin;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl;
    private javax.swing.JTable tblproduct;
    private javax.swing.JTextField txtcondition;
    private javax.swing.JTextField txtcurrent;
    private javax.swing.JTextField txtlastpurchase;
    private javax.swing.JTextField txtlastsell;
    private javax.swing.JTextField txtproid;
    private javax.swing.JTextField txtproname;
    private javax.swing.JTextField txtpropurchase;
    private javax.swing.JTextField txtprosell;
    private javax.swing.JTextField txtprotype;
    private javax.swing.JTextField txtsafe;
    // End of variables declaration//GEN-END:variables
}
