/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hpe.pss.view;



import com.hpe.pass.util.ChartBuilder;
import com.hpe.pass.util.ExportExcel;
import com.hpe.pass.util.LocationUtil;
import com.hpe.pss.vo.View_Purchase_pro;
import com.hpe.pss.vo.View_Purchase_sup;
import com.hpe.pss.biz.PurchaseBiz;
import com.hpe.pss.biz.PurchaseBizImpl;


import java.io.File;
import java.util.List;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Steve
 */
public class PurchaseGatherIFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form PurchaseGatherIFrame
     */
    List list;
    
    PurchaseBiz purdao=new PurchaseBizImpl();
    public PurchaseGatherIFrame() {
        initComponents();
        LocationUtil.setScreenCenter(this);

    }
    private void showOnTablePro(List<View_Purchase_pro> list) {
        DefaultTableModel dtm=
                (DefaultTableModel)this.tblPurchase.getModel();
        //2.清空表格信息
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
        }
        //3.显示数据表格
        for(View_Purchase_pro p : list){
            Vector vt=new Vector();
            vt.add(p.getProid());
            vt.add(p.getProname());
            vt.add(p.getPurtotamount());
            vt.add(p.getPurtotmoney());
            dtm.addRow(vt);
        }
    }
    private void showOnTableSup(List<View_Purchase_sup> list) {
        DefaultTableModel dtm=
                (DefaultTableModel)this.tblPurchase.getModel();
        //2.清空表格信息
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
        }
        //3.显示数据表格
        for(View_Purchase_sup p : list){
            Vector vt=new Vector();
            vt.add(p.getSupname());
            vt.add(p.getProname());
            vt.add(p.getPurtotamount());
            vt.add(p.getPurtotmoney());
            dtm.addRow(vt);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cobCondition = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPurchase = new javax.swing.JTable();
        btnExcel = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateStart = new com.hpe.pass.util.DateChooserJButton();
        dateEnd = new com.hpe.pass.util.DateChooserJButton();

        setClosable(true);
        setTitle("采购汇总");

        jLabel1.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel1.setText("按");

        cobCondition.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        cobCondition.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "商品", "供应商" }));

        jButton1.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jButton1.setText("汇总");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblPurchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "商品编号", "商品名称", "采购数量", "采购金额"
            }
        ));
        tblPurchase.setDragEnabled(true);
        jScrollPane1.setViewportView(tblPurchase);

        btnExcel.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnExcel.setText("导出Excel");
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jButton3.setText("退出");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jButton2.setText("生成图表");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel2.setText("从");

        jLabel3.setText("——");

        dateStart.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N

        dateEnd.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(32, 32, 32)
                .addComponent(btnExcel)
                .addGap(32, 32, 32)
                .addComponent(jButton3)
                .addGap(85, 85, 85))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(45, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cobCondition, 0, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(dateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cobCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(dateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcel)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        JFileChooser savefile = new JFileChooser();//文件选择对话框
        FileFilter filter = new FileNameExtensionFilter("Excel文件(*.xls)", "xls");
        savefile.addChoosableFileFilter(filter);//添加过滤器
        savefile.setFileFilter(filter);
        //打开文件选择对话框，showSaveDialog是保存，showOpenDialog是打开
        int flag = savefile.showSaveDialog(this); 
        File file = null;
        //如果点击了保存按钮
        if (flag == JFileChooser.APPROVE_OPTION) {
        file = savefile.getSelectedFile();//所选择的文件名（手写或选择）
        System.out.println("文件名：" + file.getAbsolutePath());
        String filename = file.getAbsolutePath();
        //截取文件扩展名（文件名长度后4位）
        String ftype = filename.substring(filename.length()-4);
        if(!ftype.equals(".xls")){
            //如果用户没有填写扩展名，自动添加扩展名.xls
            file = new File(filename+".xls");
        }
        //集合获取数据，输出到文件：ExportExcel类的printSale方法
        if(cobCondition.getSelectedItem().equals("商品")){
            ExportExcel.printPurchase(list, file);
        }
        else{
            ExportExcel.printPurchaseS(list, file);
        }  
        
        }
    }//GEN-LAST:event_btnExcelActionPerformed
    
    
        
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String start=this.dateStart.getText();
        String end=dateEnd.getText();
        if(cobCondition.getSelectedItem().equals("商品")){
            tblPurchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "商品编号", "商品名称", "采购数量", "采购金额"
            }
           ));
            list=purdao.findByConditionPro(start, end);
            showOnTablePro(list);
        }
        else{
            tblPurchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "供应商名称", "商品名称", "采购数量", "采购金额"
            }
           ));
            list=purdao.findByConditionSup(start, end);
            showOnTableSup(list);
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String charttitle;
    if(cobCondition.getSelectedItem().equals("供应商")){
        charttitle="供应商采购统计";
        ChartBuilder chart = new ChartBuilder(charttitle,list,"PurchaseSup");
        chart.pack();
        chart.setVisible(true);
    }
    else{
        charttitle="商品采购统计";
        ChartBuilder chart = new ChartBuilder(charttitle,list,"PurchasePro");
        chart.pack();
        chart.setVisible(true);
    }
    ChartBuilder chart = new ChartBuilder(charttitle,list,"PurchaseSup"); //psalelist为生成图表的数据集合
    chart.pack();
    chart.setVisible(true);
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcel;
    private javax.swing.JComboBox cobCondition;
    private com.hpe.pass.util.DateChooserJButton dateEnd;
    private com.hpe.pass.util.DateChooserJButton dateStart;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPurchase;
    // End of variables declaration//GEN-END:variables
}
