/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hpe.pss.view;


import com.hpe.pass.util.LocationUtil;
import com.hpe.pass.util.StringUtil;
import com.hpe.pss.biz.PurchaseBiz;
import com.hpe.pss.biz.PurchaseBizImpl;
import com.hpe.pss.biz.ProductBiz;
import com.hpe.pss.biz.ProductBizImpl;
import com.hpe.pss.biz.SupplierBiz;
import com.hpe.pss.biz.SupplierBizImpl;
import com.hpe.work.po.Supplier;
import com.hpe.work.po.Product;
import java.math.BigDecimal;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Steve
 */
public final class PurchaseInIFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form PurchaseInFrame
     */
    ProductBiz pbiz=new ProductBizImpl();
    PurchaseBiz purbiz=new PurchaseBizImpl();
    SupplierBiz supbiz=new SupplierBizImpl();
    public void initPurchaseTable(){
        JComboBox cobsup = new JComboBox();
        List<Supplier> suplist = supbiz.findAll();
        for(Supplier sup: suplist){
            cobsup.addItem(sup);
        }
        this.tblPurchase.getColumnModel().getColumn(6).setCellEditor(new DefaultCellEditor(cobsup)); 
    }

    public PurchaseInIFrame() {
        initComponents();
        initPurchaseTable();
        LocationUtil.setScreenCenter(this);
    }
    
    private void addPurchaseTable(Vector vt) {
        boolean flag = false;
        DefaultTableModel dtm = (DefaultTableModel) this.tblPurchase.getModel();
        for(int i=0;i<dtm.getRowCount();i++){
            if(vt.get(0) == tblPurchase.getValueAt(i, 0)){
                flag = true;
                break;
            }
        }
        if(flag == false){
            dtm.addRow(vt);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        txtCondition = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPurchase = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setClosable(true);
        setTitle("采购入库");

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "商品编号", "商品名称", "商品型号", "商品库存", "建议购买价", "建议销售价"
            }
        ));
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduct);

        btnSearch.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnSearch.setText("查询");
        btnSearch.setToolTipText("在左边输入查询条件");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel1.setText("加入采购：");

        tblPurchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "商品编号", "商品名称", "商品型号", "建议购买价", "采购量", "采购价格", "供应商"
            }
        ));
        jScrollPane2.setViewportView(tblPurchase);

        jButton1.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jButton1.setText("采购入库");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jButton3.setText("退出");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jButton4.setText("删除");
        jButton4.setToolTipText("不对真实数据产生影响");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(371, 371, 371)
                                .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)
                                .addComponent(btnSearch)))
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(432, 432, 432)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked
        //鼠标选中某行，该行信息显示到输入面板
        int selectrow = this.tblProduct.getSelectedRow();
        Integer pid = (Integer) this.tblProduct.getValueAt(selectrow, 0);
        String pname = (String) this.tblProduct.getValueAt(selectrow, 1);
        String ptype = (String) this.tblProduct.getValueAt(selectrow, 2);
        BigDecimal suggestpurchaseprice = (BigDecimal) this.tblProduct.getValueAt(selectrow, 4);
        Vector vt = new Vector();
        vt.add(pid); // vt.get(0)
        vt.add(pname);
        vt.add(ptype);
        vt.add(suggestpurchaseprice);
        //添加到采购表格
        addPurchaseTable(vt);
    }//GEN-LAST:event_tblProductMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        //模糊查询
        List<Product>list=pbiz.findByCondition(this.txtCondition.getText());
        //List<Product>list=pbiz.findAll();
        showOnTable(list);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int selectedRow = -1;
        selectedRow = this.tblPurchase.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "请择要删选除的采购信息");
            return ;
        }
        //tblPurchase :采购信息表变量名
        DefaultTableModel dtm = (DefaultTableModel) this.tblPurchase.getModel();
        dtm.removeRow(selectedRow);
        selectedRow = -1; //还原选择行号        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) this.tblPurchase.getModel();
        Object[][] purchase = new Object[dtm.getRowCount()][5];//根据具体数值数创建采购数组
        Object[][] stocks = new Object[dtm.getRowCount()][2];//商品库存数组
        //遍历表格
        for(int i=0;i<dtm.getRowCount();i++){
            //采购表
            //0编号
            purchase[i][0] = this.tblPurchase.getValueAt(i, 0);//商品编号
            //购买日期
            purchase[i][1] = new java.util.Date();
            //采购数量(验证) 
            String count_s = (String) this.tblPurchase.getValueAt(i, 4);
            if(StringUtil.checkDigit(count_s)){
            purchase[i][2] = new Integer(count_s); //采购数量
            }else{
               JOptionPane.showMessageDialog(this, "数量必须为数字！");
                return;
            }
           
            //采购价格（验证）
            String price_s = (String) this.tblPurchase.getValueAt(i, 5);
            if(StringUtil.checkDecimal(price_s)){
            purchase[i][3] = new BigDecimal(price_s) ;//采购价格
            }else{
                JOptionPane.showMessageDialog(this, "价格必须为数字！");
                return;
            }
            //供应商
            Supplier sup = (Supplier)this.tblPurchase.getValueAt(i, 6);
            purchase[i][4] = sup.getSupid();
            //商品表所需
            stocks[i][1] = this.tblPurchase.getValueAt(i, 0);
            //数量（验证）
            stocks[i][0] = this.tblPurchase.getValueAt(i, 4);
        }
        //调用批量添加
        boolean result = purbiz.purchasein(purchase, stocks);
        if(result == true){
            JOptionPane.showMessageDialog(this, "采购入库成功");
            //更新商品表
            btnSearchActionPerformed(evt);//调用查询方法
        }else{
            JOptionPane.showMessageDialog(this, "采购入库失败");
        }
        //清空采购表
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTable tblPurchase;
    private javax.swing.JTextField txtCondition;
    // End of variables declaration//GEN-END:variables

    private void showOnTable(List<Product> list) {
        DefaultTableModel dtm=
                (DefaultTableModel)this.tblProduct.getModel();
        //2.清空表格信息
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
        }
        //3.显示数据表格
        for(Product p : list){
            Vector vt=new Vector();
            vt.add(p.getProid());
            vt.add(p.getProname());
            vt.add(p.getType());
            vt.add(p.getStorecount());
            vt.add(p.getSugpurchase());
            vt.add(p.getSugsell());
            dtm.addRow(vt);
        }
    }

}
