/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hpe.pss.view;


import com.hpe.pass.util.LocationUtil;
import com.hpe.pss.vo.View_Purchase_detail;
import com.hpe.pss.biz.PurchaseBiz;
import com.hpe.pss.biz.PurchaseBizImpl;

import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Steve
 */
public class PurchaseOutIFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form PurchaseOutFram
     */
    int selectrow=-1;
    PurchaseBiz pbiz=new PurchaseBizImpl();
    public PurchaseOutIFrame() {
        initComponents();
        LocationUtil.setScreenCenter(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtConditions = new javax.swing.JTextField();
        btnQuery = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPurchase = new javax.swing.JTable();
        txtPurid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtProid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPurcount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRetamount = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtRetreason = new javax.swing.JTextField();
        dateStart = new com.hpe.pass.util.DateChooserJButton();
        dateEnd = new com.hpe.pass.util.DateChooserJButton();
        jLabel11 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("采购退货");

        btnQuery.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnQuery.setText("查询");
        btnQuery.setToolTipText("在左边输入查询条件");
        btnQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryActionPerformed(evt);
            }
        });

        tblPurchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "采购编号", "商品编号", "商品名", "采购数量", "采购价格", "供应商编号", "供应商", "采购时间"
            }
        ));
        tblPurchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPurchaseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPurchase);

        txtPurid.setEditable(false);

        jLabel1.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel1.setText("采购编号");

        txtProid.setEditable(false);

        jLabel2.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel2.setText("商品编号");

        jLabel3.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel3.setText("采购数量");

        txtPurcount.setEditable(false);

        jLabel4.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("退货数量");

        jButton2.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jButton2.setText("采购退货");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jButton3.setText("退出");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel5.setText("退货原因");

        dateStart.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N

        dateEnd.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N

        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("注意：红色字体项目为必填！");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRetreason, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(txtRetamount, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPurid, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtProid, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPurcount, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(56, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(299, 299, 299)
                                .addComponent(jButton2)
                                .addGap(82, 82, 82)
                                .addComponent(jButton3))
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(dateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(dateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtConditions, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnQuery)
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConditions, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuery)
                    .addComponent(dateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPurid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPurcount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRetreason, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRetamount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jLabel11))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryActionPerformed
        String start = this.dateStart.getText();
        String end = this.dateEnd.getText();
        String conditions = this.txtConditions.getText().trim();
        //调用业务
        List<View_Purchase_detail> list = pbiz.findByCondition(start, end, conditions);
        //显示在表格中
        showOnTable(list);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQueryActionPerformed

    private void tblPurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPurchaseMouseClicked
        this.txtPurid.setText(this.tblPurchase.getValueAt(this.tblPurchase.getSelectedRow(), 0)+"");
        this.txtProid.setText(this.tblPurchase.getValueAt(this.tblPurchase.getSelectedRow(), 1)+"");
        this.txtPurcount.setText(this.tblPurchase.getValueAt(this.tblPurchase.getSelectedRow(), 3)+"");
    }//GEN-LAST:event_tblPurchaseMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        selectrow=this.tblPurchase.getSelectedRow();
        if(selectrow == -1){
            JOptionPane.showMessageDialog(this, "请选择要退货的采购单信息");
            return;
        }
        //获取退货信息
        Integer purid = Integer.parseInt(this.txtPurid.getText());
        Integer proid = Integer.parseInt(this.txtProid.getText());
        Integer purcount = Integer.parseInt(this.txtPurcount.getText());
        //获取退货数量
        String sreturnAmount = this.txtRetamount.getText();
        //数据验证
        String regex = "[1-9][0-9]*";
        if(sreturnAmount.matches(regex)== false){
            JOptionPane.showMessageDialog(this, "请填写整数");
            return;
        }
        //转换退货数量
        Integer retamount = Integer.parseInt(sreturnAmount);
        //判断是否超过采购数量
        if(retamount>purcount){
            JOptionPane.showMessageDialog(this, "退货数量大于采购数量");
            return;
        }
        String retreason=txtRetreason.getText();
        //调用业务
        java.sql.Date  rettime = new java.sql.Date( new java.util.Date().getTime());
        boolean result = 
                pbiz.purchasereturn(purid,retamount,rettime,proid,retreason);
        if(result == true){
            JOptionPane.showMessageDialog(this, "退货成功");
            btnQueryActionPerformed(evt);
        }else{
             JOptionPane.showMessageDialog(this, "退货失败");
        }
        //清空文本框
        this.txtProid.setText("");
        this.txtPurid.setText("");
        this.txtPurcount.setText("");
        this.txtRetamount.setText("");
        selectrow = -1;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuery;
    private com.hpe.pass.util.DateChooserJButton dateEnd;
    private com.hpe.pass.util.DateChooserJButton dateStart;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPurchase;
    private javax.swing.JTextField txtConditions;
    private javax.swing.JTextField txtProid;
    private javax.swing.JTextField txtPurcount;
    private javax.swing.JTextField txtPurid;
    private javax.swing.JTextField txtRetamount;
    private javax.swing.JTextField txtRetreason;
    // End of variables declaration//GEN-END:variables

    private void showOnTable(List<View_Purchase_detail> list) {
       //1 表格模型
        DefaultTableModel dtm = (DefaultTableModel) this.tblPurchase.getModel();
        //2清空表格
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
        }
        //3 添加数据
        for(View_Purchase_detail pur:list){
            Vector vt = new Vector();
            vt.add(pur.getPurid());
            vt.add(pur.getProid());
            vt.add(pur.getProname());
            vt.add(pur.getPurcount());
            vt.add(pur.getPurunitprice());
            vt.add(pur.getSupid());
            vt.add(pur.getSupname());
            vt.add(pur.getPurdate());
            dtm.addRow(vt);
            
        }
    }

}
