/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hpe.pss.view;


import com.hpe.pass.util.ExportExcel;
import com.hpe.pass.util.LocationUtil;
import com.hpe.pss.vo.View_Purchase_detail;
import com.hpe.pss.biz.PurchaseBiz;
import com.hpe.pss.biz.PurchaseBizImpl;
import com.hpe.work.po.Purchase;
import java.io.File;

import java.math.BigDecimal;
import java.util.List;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Steve
 */
public class PurchaseIFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form PurchaseInternalFrame
     */
    PurchaseBiz pbiz=new PurchaseBizImpl();
    public PurchaseIFrame() {
        initComponents();
//        List<Purchase>list=pbiz.findAll(); 
//        showOnTable(list); 
        LocationUtil.setScreenCenter(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPurchase = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtPurid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtProid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPurdate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPurcount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPurprice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSupid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRetamount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtRetdate = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        cobCondition = new javax.swing.JComboBox();
        txtConditions = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtRetreason = new javax.swing.JTextField();
        dateStart = new com.hpe.pass.util.DateChooserJButton();
        dateEnd = new com.hpe.pass.util.DateChooserJButton();

        setClosable(true);
        setTitle("采购查询");
        setToolTipText("");

        tblPurchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "采购单号", "商品名称", "采购数量", "采购价格", "供应商名称", "采购日期"
            }
        ));
        tblPurchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPurchaseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPurchase);
        if (tblPurchase.getColumnModel().getColumnCount() > 0) {
            tblPurchase.getColumnModel().getColumn(2).setResizable(false);
            tblPurchase.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel1.setText("采购编号");

        txtPurid.setEditable(false);
        txtPurid.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel2.setText("商品编号");

        txtProid.setEditable(false);
        txtProid.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel3.setText("采购日期");

        txtPurdate.setEditable(false);
        txtPurdate.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel4.setText("采购数量");

        txtPurcount.setEditable(false);
        txtPurcount.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel5.setText("采购价格");

        txtPurprice.setEditable(false);
        txtPurprice.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel6.setText("供应商编号");

        txtSupid.setEditable(false);
        txtSupid.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        jLabel7.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel7.setText("退货数量");

        txtRetamount.setEditable(false);
        txtRetamount.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel8.setText("退货日期");

        txtRetdate.setEditable(false);
        txtRetdate.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        btnExit.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnExit.setText("退出");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        cobCondition.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        cobCondition.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "时间段", "商品名称", "供应商名称" }));

        txtConditions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConditionsActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnSearch.setText("搜索");
        btnSearch.setToolTipText("在左边输入查询条件");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel9.setText("---");

        jLabel10.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel10.setText("退货原因");

        txtRetreason.setEditable(false);
        txtRetreason.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        dateStart.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        dateEnd.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtRetreason, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(204, 204, 204)
                                .addComponent(cobCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(txtConditions, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 96, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtPurprice, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtPurid)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtProid, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(txtSupid))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPurcount, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(10, 10, 10)
                                .addComponent(txtRetamount)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtRetdate, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPurdate))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(892, 892, 892)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(dateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSearch))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 5, Short.MAX_VALUE)
                                .addComponent(cobCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtConditions))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(txtProid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txtPurcount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPurdate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtPurid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPurprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtSupid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRetamount)
                            .addComponent(jLabel8)
                            .addComponent(txtRetdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(txtRetreason, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPurchaseMouseClicked
        //鼠标选中某行，该行信息显示到输入面板
        List<Purchase>list=pbiz.findAll();
        int row=this.tblPurchase.getSelectedRow();
        Purchase p=list.get(row);
        this.txtPurid.setText(p.getPurid()+"");
        this.txtProid.setText(p.getProid()+"");
        this.txtPurdate.setText(p.getPurdate()+"");
        this.txtPurcount.setText(p.getPurcount()+"");
        this.txtPurprice.setText(p.getPurunitprice()+"");
        this.txtSupid.setText(p.getSupid()+"");
        this.txtRetamount.setText(p.getRetamount()+"");
        this.txtRetdate.setText(p.getRettime()+"");
        this.txtRetreason.setText(p.getRetreason()+"");
    }//GEN-LAST:event_tblPurchaseMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtConditionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConditionsActionPerformed
        // add your handling code here:
    }//GEN-LAST:event_txtConditionsActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
        //！！//一定要创建视图吗（或者修改表）？商品名称
        String start = this.dateStart.getText();
        String end = this.dateEnd.getText();
        String conditions = this.txtConditions.getText().trim();
        List<View_Purchase_detail> list;
        switch((String)cobCondition.getSelectedItem()){
            case "商品名称":
            case "供应商名称":
            case "时间段":  list= pbiz.findByCondition(start, end, conditions);
                          showOnTable(list);break;
            default:break;
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox cobCondition;
    private com.hpe.pass.util.DateChooserJButton dateEnd;
    private com.hpe.pass.util.DateChooserJButton dateStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPurchase;
    private javax.swing.JTextField txtConditions;
    private javax.swing.JTextField txtProid;
    private javax.swing.JTextField txtPurcount;
    private javax.swing.JTextField txtPurdate;
    private javax.swing.JTextField txtPurid;
    private javax.swing.JTextField txtPurprice;
    private javax.swing.JTextField txtRetamount;
    private javax.swing.JTextField txtRetdate;
    private javax.swing.JTextField txtRetreason;
    private javax.swing.JTextField txtSupid;
    // End of variables declaration//GEN-END:variables

    private void clearInput() {
        this.txtProid.setText("");
        this.txtPurcount.setText("");
        this.txtPurdate.setText("");
        this.txtPurid.setText("");
        this.txtPurprice.setText("");
        this.txtRetamount.setText("");
        this.txtRetdate.setText("");
        this.txtSupid.setText("");//To change body of generated methods, choose Tools | Templates.
    }

    private void showOnTable(List<View_Purchase_detail> list) {
        DefaultTableModel dtm=
                (DefaultTableModel)this.tblPurchase.getModel();
        //2.清空表格信息
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
        }
        //3.显示数据表格
        for(View_Purchase_detail p : list){
            Vector vt=new Vector();
            vt.add(p.getPurid());
            vt.add(p.getProname());
            vt.add(p.getPurcount());
            vt.add(p.getPurunitprice());
            vt.add(p.getSupname());
            vt.add(p.getPurdate());
            dtm.addRow(vt);
        }
    }
}
