/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hpe.pss.view;

import com.hpe.pss.biz.CustomerBiz;
import com.hpe.pss.biz.CustomerBizImpl;
import com.hpe.pss.biz.RecycleBiz;
import com.hpe.pss.biz.RecycleBizImpl;
import com.hpe.work.po.Customer;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Steve
 */
public class RecycleIFrame extends javax.swing.JInternalFrame {
    RecycleBiz rbiz=new RecycleBizImpl();

    public RecycleIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblcustomer = new javax.swing.JTable();
        btnlog = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("回收站");

        tblcustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "客户编号", "客户名称", "客户手机", "客户电话", "客户地址"
            }
        ));
        tblcustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblcustomer);

        btnlog.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnlog.setText("载入");
        btnlog.setToolTipText("加载全部客户信息");
        btnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jButton1.setText("恢复");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnlog)
                .addGap(108, 108, 108)
                .addComponent(jButton1)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlog)
                    .addComponent(jButton1))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblcustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcustomerMouseClicked
        int n=(int)tblcustomer.getValueAt(tblcustomer.getSelectedRow(), 0);
        
    }//GEN-LAST:event_tblcustomerMouseClicked

    private void btnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogActionPerformed
        List<Customer> list = rbiz.findall();
        showOnTable(list);
    }//GEN-LAST:event_btnlogActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    boolean result = rbiz.recycle((int)tblcustomer.getValueAt(tblcustomer.getSelectedRow(), 0));
        if(result == true){
            JOptionPane.showMessageDialog(this, "恢复成功");
            btnlogActionPerformed(evt);
            return;
        }else{
        JOptionPane.showMessageDialog(this, "恢复失败");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    public void showOnTable( List<Customer> list){
        //1.获取制定表格（tblProduct）模型
        DefaultTableModel dtm = (DefaultTableModel) this.tblcustomer.getModel();
        //2.清空表格信息
        while(dtm.getRowCount() > 0){
            dtm.removeRow(0);
        }
        //3.显示数据
        for(Customer p : list){
            Vector vt = new Vector();
            vt.add(p.getCusid());
            vt.add(p.getCusname()); 
            vt.add(p.getCustel());
            vt.add(p.getCusmobile());
            vt.add(p.getCusaddr());
           dtm.addRow(vt);
        }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlog;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblcustomer;
    // End of variables declaration//GEN-END:variables
}
