/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hpe.pss.view;


import com.hpe.pass.util.LocationUtil;
import com.hpe.pass.util.StringUtil;
import com.hpe.pss.biz.ReturnBiz;
import com.hpe.pss.biz.ReturnBizImpl;
import com.hpe.work.po.ReturnProuct;
import java.text.SimpleDateFormat;

import java.util.List;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class ReturnSellIFrame extends javax.swing.JInternalFrame {
 public static LocationUtil local;
    /**
     * Creates new form ReturnSellIFrame
     */
    ReturnBiz pbiz = new ReturnBizImpl();
    public ReturnSellIFrame() {
        initComponents();
        local.setScreenCenter(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblreturn = new javax.swing.JTable();
        txtcondition = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtproid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtproname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtreturnamount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtreturndate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcusname = new javax.swing.JTextField();
        btnreturn = new javax.swing.JButton();
        btnexittwo = new javax.swing.JButton();
        btnno = new javax.swing.JButton();
        btnlog = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtretid = new javax.swing.JTextField();

        setClosable(true);
        setTitle("退货管理");

        tblreturn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "商品编号", "商品名称", "退货数量", "退货时间", "客户名称", "退货编号"
            }
        ));
        tblreturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblreturnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblreturn);

        txtcondition.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        btnsearch.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnsearch.setText("查询");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel1.setText("商品编号：");

        txtproid.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("商品名称：");

        txtproname.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("退货数量：");

        txtreturnamount.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("退货时间：");

        txtreturndate.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel5.setText("客户名称：");

        txtcusname.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        btnreturn.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnreturn.setText("退货");
        btnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnActionPerformed(evt);
            }
        });

        btnexittwo.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnexittwo.setText("退出");
        btnexittwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexittwoActionPerformed(evt);
            }
        });

        btnno.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnno.setText("取消");
        btnno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnoActionPerformed(evt);
            }
        });

        btnlog.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnlog.setText("载入");
        btnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel6.setText("退货编号：");

        txtretid.setEditable(false);
        txtretid.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnlog)
                    .addComponent(txtreturndate, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(txtproid))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnreturn)
                        .addGap(18, 18, 18)
                        .addComponent(btnno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnexittwo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcusname))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtproname, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtretid))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtreturnamount, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtproid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtreturnamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txtreturndate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txtretid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtproname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtcusname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnexittwo)
                        .addComponent(btnno)
                        .addComponent(btnreturn))
                    .addComponent(btnlog))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtcondition, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnsearch)
                .addGap(140, 140, 140))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblreturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblreturnMouseClicked
                                               
        
        int row = this.tblreturn.getSelectedRow();
        this.txtproid.setText(this.tblreturn.getValueAt(row,0)+"");
        this.txtproname.setText(this.tblreturn.getValueAt(row,1)+"");
        this.txtreturnamount.setText(this.tblreturn.getValueAt(row, 2)+"");
        this.txtreturndate.setText(this.tblreturn.getValueAt(row, 3)+"");
        this.txtcusname.setText(this.tblreturn.getValueAt(row, 4)+"");
         this.txtretid.setText(this.tblreturn.getValueAt(row, 5)+"");
        this.btnreturn.setEnabled(true);
    }//GEN-LAST:event_tblreturnMouseClicked

    private void btnexittwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexittwoActionPerformed
          this.dispose();
    }//GEN-LAST:event_btnexittwoActionPerformed

    private void btnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnActionPerformed
        
        String Proid = this.txtproid.getText().trim();
        String proname = this.txtproname.getText().trim();
        String returnamount = this.txtreturnamount.getText().trim();
        String returnDate= this.txtreturndate.getText().trim();
        String cusname = this.txtcusname.getText().trim();
       //数据验证
        if(StringUtil.checkLength(Proid)==false){
            JOptionPane.showMessageDialog(this,"商品编号不能为空");
            return ;
        }
          String regex = "[1-9][0-9]*";
        if(returnamount.matches(regex)== false){
            JOptionPane.showMessageDialog(this, "请填写整数");
            return;
        }
        if(StringUtil.checkLength(returnamount)==false){
           JOptionPane.showMessageDialog(this,"销售数量不能为空");
           return ;
        }
        int proid = Integer.parseInt(this.txtproid.getText());
        int returnAmount = Integer.parseInt(this.txtreturnamount.getText());
        if(JOptionPane.showConfirmDialog(this, "确认退货")==2)return;
        else;
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); 
        
        java.sql.Date returndate = java.sql.Date.valueOf(returnDate);
        ReturnProuct p = new ReturnProuct(proid,proname,returnAmount,returndate,cusname,null);
        //调用业务类
        boolean result = pbiz.add(p);
        if(result == true){
            JOptionPane.showMessageDialog(this, "退货成功");
            List<ReturnProuct> list = pbiz.findAll();
           boolean update = pbiz.updateStoreCount(returnAmount,proid);
            
            showOnTable(list);
        }
        else{
             JOptionPane.showMessageDialog(this, "退货失败");
        }
        clearInput();
    }//GEN-LAST:event_btnreturnActionPerformed

    private void btnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogActionPerformed
          List<ReturnProuct> list = pbiz.findAll();
          showOnTable(list);
    }//GEN-LAST:event_btnlogActionPerformed

    private void btnnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnoActionPerformed
           clearInput();

    }//GEN-LAST:event_btnnoActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
          String condition = this.txtcondition.getText().trim();
          List<ReturnProuct> list = pbiz.findByCondition(condition);
          showOnTable(list);
    }//GEN-LAST:event_btnsearchActionPerformed

    private void showOnTable(List<ReturnProuct> list) {
        DefaultTableModel dtm = (DefaultTableModel) this.tblreturn.getModel();
        //2.清空表中信息
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
        }
            //3.显示数据
            for(ReturnProuct p:list){
                Vector vt = new Vector();
                vt.add(p.getProid());
                vt.add(p.getProname());
                vt.add(p.getReturnamount());
                vt.add(p.getReturndate());
                vt.add(p.getCusname());
                vt.add(p.getRetid());
              
                dtm.addRow(vt);
                
            }
    }
          private void clearInput() {
       this.txtproid.setText("");
       this.txtproname.setText("");
       this.txtreturnamount.setText("");
       this.txtreturndate.setText("");
       this.txtcusname.setText("");
       this.txtretid.setText("");
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexittwo;
    private javax.swing.JButton btnlog;
    private javax.swing.JButton btnno;
    private javax.swing.JButton btnreturn;
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblreturn;
    private javax.swing.JTextField txtcondition;
    private javax.swing.JTextField txtcusname;
    private javax.swing.JTextField txtproid;
    private javax.swing.JTextField txtproname;
    private javax.swing.JTextField txtretid;
    private javax.swing.JTextField txtreturnamount;
    private javax.swing.JTextField txtreturndate;
    // End of variables declaration//GEN-END:variables
}
