/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hpe.pss.view;


import com.hpe.pass.util.LocationUtil;
import com.hpe.pss.biz.ProductBiz;
import com.hpe.pss.biz.ProductBizImpl;
import com.hpe.pss.biz.SellManagerBiz;
import com.hpe.pss.biz.SellManagerBizImpl;
import com.hpe.work.po.Product;
import com.hpe.work.po.SellManager;
import java.math.BigDecimal;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author lenovo
 */
public class SellManagerIFrame extends javax.swing.JInternalFrame {
 public static LocationUtil local;
    /**
     * Creates new form SellManagerIFrame
     */ 
   // productbiz pbiz1 = new productbiziml();
    ProductBiz pbiz1 = new ProductBizImpl();
    SellManagerBiz pbiz  = new SellManagerBizImpl();
    private Object NoUtil;
    public SellManagerIFrame() {
        initComponents();
        local.setScreenCenter(this);
        initPurchaseTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblproduct = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblsell = new javax.swing.JTable();
        txtcondition = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        btnsellout = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("销售出库");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tblproduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "商品编号", "商品名称", "商品类型", "商品库存"
            }
        ));
        tblproduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblproductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblproduct);

        tblsell.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "商品编号", "商品名称", "库存", "销售数量", "销售价格", "客户姓名"
            }
        ));
        jScrollPane2.setViewportView(tblsell);

        txtcondition.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        btnsearch.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnsearch.setText("查询");
        btnsearch.setToolTipText("在左边输入查询条件");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btnsellout.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnsellout.setText("销售出库");
        btnsellout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselloutActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btndelete.setText("删除");
        btndelete.setToolTipText("不删除数据库内容");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnexit.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnexit.setText("退出");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel1.setText("加入销售：");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnsellout)
                                .addGap(35, 35, 35)
                                .addComponent(btndelete)
                                .addGap(18, 18, 18)
                                .addComponent(btnexit)
                                .addGap(115, 115, 115))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtcondition, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnsearch)
                                .addGap(92, 92, 92)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsearch)
                    .addComponent(txtcondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(119, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnsellout, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(btnexit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btndelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
          String condition = this.txtcondition.getText().trim();
          List<Product> list = pbiz1.findByCondition(condition);
          showOnTable1(list);
    }//GEN-LAST:event_btnsearchActionPerformed

    private void tblproductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblproductMouseClicked
       int selectrow = this.tblproduct.getSelectedRow();
        Integer proid = (Integer) this.tblproduct.getValueAt(selectrow, 0);
        String proname = (String) this.tblproduct.getValueAt(selectrow, 1);
      // String protype = (String) this.tblproduct.getValueAt(selectrow, 2);
        Integer storecount = (Integer) this.tblproduct.getValueAt(selectrow, 3);
        
        Vector vt = new Vector();
        vt.add(proid); // vt.get(0)
        vt.add(proname);
        vt.add(storecount);
        //添加到采购表格
        addPurchaseTable(vt);
    }//GEN-LAST:event_tblproductMouseClicked
  private void addPurchaseTable(Vector vt) {
        boolean flag = false;
        DefaultTableModel dtm = (DefaultTableModel) this.tblsell.getModel();
        for(int i=0;i<dtm.getRowCount();i++){
            if(vt.get(0) == tblsell.getValueAt(i, 0)){
                flag = true;
                break;
            }
        }
        if(flag == false){
            dtm.addRow(vt);
        }
    }
    private void btnselloutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselloutActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) this.tblsell.getModel();
        Object[][] sellManager = new Object[dtm.getRowCount()][5];//根据具体数值数创建采购数组
        Object[][] product = new Object[dtm.getRowCount()][2];//商品库存数组
        //遍历表格
        for(int i=0;i<dtm.getRowCount();i++){
         //sellManager[i][0] = NoUtil.createSelid();//采购单号
            sellManager[i][0] = this.tblsell.getValueAt(i, 0);//商品编号
            product[i][0] = this.tblsell.getValueAt(i, 2);
            sellManager[i][1] = this.tblsell.getValueAt(i, 1);//采购数量
            product[i][1] = this.tblsell.getValueAt(i, 0);
            sellManager[i][2] = this.tblsell.getValueAt(i, 3);//采购价格
            sellManager[i][3] = this.tblsell.getValueAt(i,4);
            sellManager[i][4] = ((SellManager)this.tblsell.getValueAt(i,5)).getCusname();
        }
        //调用批量添加
        boolean result = pbiz.sellout(sellManager, product);
        if(result == true){
            JOptionPane.showMessageDialog(this, "销售出库成功");
            //更新商品表
           // btnQueryActionPerformed(evt);//调用查询方法
        }else{
            JOptionPane.showMessageDialog(this, "销售出库失败");
        }
        //清空采购表
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
        }
    }//GEN-LAST:event_btnselloutActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
       //窗口关闭从map中移除
        
    }//GEN-LAST:event_formInternalFrameClosed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
           int selectedRow = -1;
        selectedRow = this.tblsell.getSelectedRow();  
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "请选择要删除的信息");
            return ;
        }
        //tblPurchase :采购信息表变量名
        DefaultTableModel dtm = (DefaultTableModel) this.tblsell.getModel();
        dtm.removeRow(selectedRow);
        selectedRow = -1; //还原选择行号
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnexitActionPerformed

  private void  showOnTable (List<SellManager> list) {
        DefaultTableModel dtm = (DefaultTableModel) this.tblsell.getModel();
        //2.清空表中信息
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
        }
            //3.显示数据
            for(SellManager p:list){
                Vector vt = new Vector();
                vt.add(p.getProid());
                vt.add(p.getProname());
           
                vt.add(p.getProcount());
                vt.add(p.getProprice());
                vt.add(p.getCusname());
            
                dtm.addRow(vt);
                
            }
    }
    private void showOnTable1(List<Product> list1) {
        DefaultTableModel dtm = (DefaultTableModel) this.tblproduct.getModel();
        //2.清空表中信息
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
        }
            //3.显示数据
            for(Product p:list1){
                Vector vt = new Vector();
                vt.add(p.getProid());
                vt.add(p.getProname());
                vt.add(p.getType());
               // vt.add(p.get);
                vt.add(p.getSafeamount());
               dtm.addRow(vt);
                
            }
    }
public void initPurchaseTable(){
        JComboBox cobsup = new JComboBox();
        List<SellManager> suplist = pbiz.findAll();
        for(SellManager sup: suplist){
            cobsup.addItem(sup);       
 }
        this.tblsell.getColumnModel().getColumn(5).setCellEditor(new DefaultCellEditor(cobsup)); 

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnsellout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblproduct;
    private javax.swing.JTable tblsell;
    private javax.swing.JTextField txtcondition;
    // End of variables declaration//GEN-END:variables
}
