/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hpe.pss.view;


import com.hpe.pass.util.LocationUtil;
import com.hpe.pass.util.StringUtil;
import com.hpe.pss.biz.SupplierBiz;
import com.hpe.pss.biz.SupplierBizImpl;
import com.hpe.work.po.Supplier;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class SupplierIFrame extends javax.swing.JInternalFrame {
 SupplierBiz pbiz = new SupplierBizImpl();
 public static LocationUtil local;
    /**
     * Creates new form supplierFrame
     */
    public SupplierIFrame() {
        initComponents();
        local.setScreenCenter(this);
          this.btnSave.setEnabled(false);
        this.btnDelete.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSupid = new javax.swing.JTextField();
        txtSubname = new javax.swing.JTextField();
        txtSupaddr = new javax.swing.JTextField();
        txtSuptel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtOwner = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtJob = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMoblie = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnQuxiao = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("供应商管理");

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "供应商编号", "供应商简称", "负责人", "称谓", "供应商电话", "供应商手机", "供应商地址", "最后供应时间"
            }
        ));
        tblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSupplier);

        jLabel1.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel1.setText("供应商编号");

        jLabel2.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("供应商简称");

        jLabel3.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel3.setText("供应商地址");

        txtSupid.setEditable(false);
        txtSupid.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        txtSupid.setEnabled(false);

        txtSubname.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        txtSupaddr.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        txtSupaddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupaddrActionPerformed(evt);
            }
        });

        txtSuptel.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel5.setText("负责人");

        txtOwner.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel4.setText("供应商电话");

        jLabel6.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel6.setText("称谓");

        txtJob.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel8.setText("供应商手机");

        txtMoblie.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        txtMoblie.setText(" ");

        jLabel9.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel9.setText("最后供货时间");

        txtDate.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSupid, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(456, 456, 456))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSupaddr)
                                .addGap(50, 50, 50))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(263, 263, 263)
                                        .addComponent(jLabel2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtJob, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSuptel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSubname, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMoblie, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(txtOwner)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSupid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtSubname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtSuptel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtMoblie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSupaddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(50, 50, 50))))
        );

        btnSave.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnSave.setText("修改并保存");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnQuxiao.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnQuxiao.setText("取消");
        btnQuxiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuxiaoActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnDelete.setText("删除");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnExit.setText("退出");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnUpdate.setFont(btnUpdate.getFont().deriveFont(btnUpdate.getFont().getStyle() | java.awt.Font.BOLD, 24));
        btnUpdate.setText("载入");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnAdd.setText("新增");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N

        btnSearch.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        btnSearch.setText("查询");
        btnSearch.setToolTipText("在左边输入查询条件");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("注意：红色字体项目为必填！");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addGap(26, 26, 26)
                        .addComponent(btnAdd)
                        .addGap(37, 37, 37)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuxiao)
                        .addGap(35, 35, 35)
                        .addComponent(btnDelete)
                        .addGap(27, 27, 27)
                        .addComponent(btnExit)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(82, 82, 82))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExit)
                            .addComponent(btnDelete)
                            .addComponent(btnQuxiao)
                            .addComponent(btnSave)
                            .addComponent(btnAdd)
                            .addComponent(btnUpdate))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSupaddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupaddrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupaddrActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
          List<Supplier> list = pbiz.findAll();
        //显示list中的信息
        showOnTable(list);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //int supid = this.txtSupid.getText().trim();
        String supname = this.txtSubname.getText().trim();
        String owner = this.txtOwner.getText().trim();
        String job = this.txtJob.getText().trim();
        String suptel = this.txtSuptel.getText().trim();
        String mobile = this.txtMoblie.getText().trim();
        String supaddr = this.txtSupaddr.getText().trim();
        String lastpurchase_s = this.txtDate.getText().trim();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
          java.sql.Date lastpurchase = java.sql.Date.valueOf(lastpurchase_s);
        Supplier  p = new Supplier(null,supname,owner,job,suptel,mobile,supaddr,lastpurchase);

       boolean result = pbiz.add(p);
        if(result == true){
            JOptionPane.showMessageDialog(this,"添加成功");
            List<Supplier> list = pbiz.findAll();
           showOnTable(list);
        }else{
            JOptionPane.showMessageDialog(this,"添加失败");
        }
        //清空面板
        clearInput();

    }//GEN-LAST:event_btnAddActionPerformed

    private void tblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupplierMouseClicked
         int row = this.tblSupplier.getSelectedRow();
        this.txtSupid.setText(this.tblSupplier.getValueAt(row ,0)+"");
        this.txtSubname.setText(this.tblSupplier.getValueAt(row, 1)+"");
        this.txtOwner.setText(this.tblSupplier.getValueAt(row, 2)+"");
        this.txtJob.setText(this.tblSupplier.getValueAt(row, 3)+"");
        this.txtSuptel.setText(this.tblSupplier.getValueAt(row, 4)+"");
        this.txtMoblie.setText(this.tblSupplier.getValueAt(row, 5)+"");
        this.txtSupaddr.setText(this.tblSupplier.getValueAt(row, 6)+"");
        this.txtDate.setText(this.tblSupplier.getValueAt(row, 7)+"");
        //
        this.btnDelete.setEnabled(true);
       this.btnSave.setEnabled(true);
    }//GEN-LAST:event_tblSupplierMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int answer = JOptionPane.showConfirmDialog(this,"您确定要删除吗？");
        if(answer == JOptionPane.YES_OPTION){
             //删除商品
             int supid = Integer.parseInt(this.txtSupid.getText());
            boolean result = pbiz.delete(supid);   
           
            if(result == true){
                 JOptionPane.showMessageDialog(this,"删除成功");
                 List<Supplier> list = pbiz.findAll();
                 showOnTable(list);
             }else{
                JOptionPane.showMessageDialog(this,"删除失败");
             }
        }else{
             JOptionPane.showMessageDialog(this,"取消删除");
        }
        
       
        //清空面板
        clearInput();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
          this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnQuxiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuxiaoActionPerformed
        // TODO add your handling code here:
          clearInput();
        this.btnSave.setEnabled(false);
        this.btnDelete.setEnabled(false);
    }//GEN-LAST:event_btnQuxiaoActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        int supid = Integer.parseInt(this.txtSupid.getText());
        String supname = this.txtSubname.getText().trim();
        String suptel = this.txtSuptel.getText().trim();
        String supaddr = this.txtSupaddr.getText().trim();
        String owner = this.txtOwner.getText().trim();
        String job = this.txtJob.getText().trim();
        String mobile = this.txtMoblie.getText().trim();
        String last = this.txtDate.getText().trim();
    
       // SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
          java.sql.Date lastpurchase = java.sql.Date.valueOf(last);
      
        Supplier p = new Supplier(supid,supname,owner,job,suptel,mobile,supaddr,lastpurchase);
        System.out.println(p);
        boolean result = pbiz.update(p);
        
        if(result == true){
            JOptionPane.showMessageDialog(this,"修改成功");
            List<Supplier> list = pbiz.findAll();
            showOnTable(list);
        }else{
             JOptionPane.showMessageDialog(this,"修改失败");
        }
        //清空面板
        clearInput();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
         String condition = this.txtSearch.getText().trim();
        List<Supplier> list = pbiz.findByCondition(condition);
        showOnTable(list);
    }//GEN-LAST:event_btnSearchActionPerformed
 public void showOnTable( List<Supplier> list){
        //1.获取制定表格（tblProduct）模型
        DefaultTableModel dtm = (DefaultTableModel) this.tblSupplier.getModel();
        //2.清空表格信息
        while(dtm.getRowCount() > 0){
            dtm.removeRow(0);
        }
        //3.显示数据
        for(Supplier p : list){
            Vector vt = new Vector();
            vt.add(p.getSupid());
            vt.add(p.getSupname()); 
            vt.add(p.getOwner());
            vt.add(p.getJob());
            vt.add(p.getSuptel());
            vt.add(p.getMobile());
            vt.add(p.getSupaddr());
            vt.add(p.getLastpurchase());
           dtm.addRow(vt);
        }
}
public void clearInput(){
  this.txtSupid.setText("");
    this.txtSubname.setText("");
    this.txtOwner.setText("");
    this.txtJob.setText("");
    this.txtSuptel.setText("");
    this.txtMoblie.setText("");
    this.txtSupaddr.setText("");
    this.txtDate.setText("");

}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnQuxiao;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtJob;
    private javax.swing.JTextField txtMoblie;
    private javax.swing.JTextField txtOwner;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSubname;
    private javax.swing.JTextField txtSupaddr;
    private javax.swing.JTextField txtSupid;
    private javax.swing.JTextField txtSuptel;
    // End of variables declaration//GEN-END:variables



}
